import Header from '@/components/Header'
import React from 'react'

export default function Terms() {
  return (
    <div>
      <Header />
      <div className='flex flex-col gap-20 px-5 pb-40 pt-16 sm:px-20 lg:gap-40'>
        <div className='prose-sm lg:prose-base mt-5'>
          <h1>Terms of Use</h1>
          <div>
            <h1>Terms and Conditions of Use</h1>
            <p>
              These are the Company Terms and Conditions of Use (‘Terms’) which form a legal and binding agreement
              amongst Sportoni Technologies (referred to as the ‘Company’, ‘Sportoni Technologies’, ‘Us’, ‘We’ or ‘Our’)
              and any person (‘You’/ ‘Your’/ ‘User’) accessing:
            </p>
            <ul>
              <li>
                Our website –{' '}
                <a href='http://www.ludowala.co' target='_blank' rel='noopener noreferrer'>
                  www.ludowala.co
                </a>{' '}
                (‘Website’) and the LudoWala mobile application (‘App’) including any subdomains of the Website, or
                related top-level domains including{' '}
                <a href='http://www.ludowala.co' target='_blank' rel='noopener noreferrer'>
                  www.ludowala.co
                </a>
                , mobile sites, apps, APIs, widgets (hereinafter collectively referred as ‘the Platform’), and/or;
              </li>
              <li>
                any data, information, text, graphics, video, sound, pictures, and any other materials appearing, sent,
                uploaded, communicated, transmitted, or otherwise made available via the Platform (jointly referred to
                as the ‘Content’) for participating in various contests and games hosted on the Platform (‘Services’ /
                ‘Games’).
              </li>
            </ul>
            <p>
              Such User (as described above) shall be bound by these Terms, Privacy Policy (Privacy Policy) and all
              other rules, regulations, and terms of use (including Privacy Policy) referred to herein or provided by
              Company in relation to any Company Services. This document is an electronic record in terms of the
              Information Technology Act, 2000 and rules there under as applicable and various other statutes. This
              electronic record is generated by a computer system and does not require any physical or digital
              signatures.
            </p>
            <p>
              You acknowledge and agree that by using, or otherwise accessing the Company Platform and Company Services,
              you agree to be bound by these Terms and our Privacy Policy (Privacy Policy). You acknowledge that we
              provide use and access to our Platform and Services to you, subject to these Terms. You agree and
              acknowledge that you have completely read and understood these Terms and the Privacy Policy, incorporated
              herein by reference, as amended from time to time. You agree, covenant, and undertake to be bound by the
              specific rules and regulations of each of the Games as applicable.
            </p>
            <p>
              We reserve the right to amend, modify, update, terminate, supplement or otherwise amend all or any of the
              Terms, Privacy Policy, rules, or regulations on the Platform at any time by publishing new Terms. Company
              may, at its sole discretion, also notify the User of any change or modification in these Terms, Privacy
              Policy, rules, regulations, and terms of use referred to herein or provided by Company, by way of sending
              an email to the User’s registered email address or posting notifications in the User accounts. The User
              may then exercise the options provided in such an email or notification to indicate non-acceptance of the
              modified Terms, rules, regulations, and terms of use referred to herein or provided by Company. If such
              options to indicate non-acceptance are not exercised by the User within the time frame prescribed in the
              email or notification, the User will be deemed to have accepted the modified Terms, rules, regulations,
              and terms of use referred to herein or provided by Company.
            </p>
            <p>
              If the User does not accept the modified Terms, rules, regulations, and terms of use referred to herein or
              provided by Company, we reserve the right to deny access to the Platform and Services to the User. If the
              User does not accept the modified Privacy Policy, we reserve the right to deny access to the Platform and
              Services to the User to the extent such modified terms of the Privacy Policy are required to provide
              access to the Platform and Services.
            </p>
            <p>
              Participation in any Games or contest on the Company Platform or viewing of certain Content may be subject
              to further terms and conditions as may be notified by us from time to time on the Website or otherwise.
              You should ensure that you have read, understood and agree to abide by the rules and regulations of the
              Games, contest, tournament available through the Company Platform.
            </p>
            <p>Company may, at its sole and absolute discretion:</p>
            <ul>
              <li>Move or remove any Content that is available or posted by a User on the Platform.</li>
              <li>
                Establish general practices and limits concerning the use of the Platform and modify these practices,
                limits and thresholds at its discretion, from time to time, and such changes shall be notified and/or
                included within updated Terms as deemed fit by Company.
              </li>
              <li>
                Assign its rights and liabilities to all User accounts hereunder to any entity (post such assignment,
                intimation of such assignment shall be sent to all Users to their registered email addresses).
              </li>
            </ul>
            <p>
              Your use of information on our Platform including results, fixture lists, statistics, data, and news
              posted on our Platform is at your own risk. Other than as expressly set out in these Terms and to the
              extent permitted by law, we make no warranty as to the accuracy or reliability of the information
              contained on our Platform or in our publications (including, but not limited to, any Content or
              information generated on our Platform by or on behalf of us, and any third-party content on our Platform).
              We and our related entities, directors, officers, and agents disclaim all liability and responsibility for
              any loss or damage (whether direct or indirect) that may be suffered by any recipient through relying on
              anything contained in, or omitted from our Platform or publications.
            </p>
            <p>
              You hereby unconditionally and irrevocably, expressly agree to the transfer of your personal data and
              information (including sensitive data) to Us and to such third parties who we contract with to provide you
              with the Services.
            </p>
            <h2>B. Description of Services Offered</h2>
            <p>
              Subject to the Users compliance with these Terms, Company gives Users a personal, royalty-free,
              non-assignable, non-sublicensable, non-transferable, non-exclusive, and revocable limited right to access
              and use the Platform that is provided as part of the Services. This right is for the sole purpose of
              enabling the own personal private use from Users to play Games of skill as hosted on the Platform, in the
              manner prescribed under these Terms and not for any commercial purposes, in India and only until the User
              is bound by these Terms.
            </p>
            <p>
              The Services may change or be modified from time to time without prior notice or communication. Company
              reserves the right to change, modify or delete the Platform or Services, information, and Terms listed
              thereon at any time without prior notice.
            </p>
            <p>
              The Services may include advertisements, which may be targeted to the Content or information on the
              Services, queries made through the Services, or any other information. The types and extent of advertising
              by Company on the Services are subject to change.
            </p>
            <p>
              When access Games are included in the Services, the specific rules, scoring, controls and guidelines for
              each game can be found within the game itself. The Users agree to and shall comply with such rules,
              scoring, controls and guidelines etc.
            </p>
            <p>
              Any charges levied on Users for accessing the Services, including but not limited to internet connection
              and/or mobile or data charges are solely the responsibility of such Users.
            </p>
            <h2>C. User Registration</h2>
            <p>
              In order to access the Website or fully utilize the Platform offered by the Company, a User is required to
              register on the Platform. You are not authorized to access any of our Platform, until you have been
              granted an Account (defined below).
            </p>
            <p>
              If you wish to become a registered User, you will need to create an account (‘Account’) on our Platform.
              Each User is only permitted to open one Account. Company reserves the right to terminate or suspend any
              duplicate accounts.
            </p>
            <p>
              In order to apply for an Account, Company may require you to register by completing a form and providing
              certain details (listed below), in accordance with the instructions on the Platform:
            </p>
            <ul>
              <li>Full Name</li>
              <li>E-mail address</li>
              <li>Password</li>
              <li>State of Residence</li>
              <li>Gender</li>
              <li>Date of Birth</li>
              <li>Mobile Number</li>
              <li>Bank Account Number</li>
              <li>Permanent Account Number Card (PAN Card)</li>
              <li>Government issued Identity Documents (for know your customer checks)</li>
            </ul>
            <p>
              You can also register or log in through your Google or personal e-mail address. You may also be required
              to provide your mobile number for verification purposes and verify such mobile number using a one-time
              passcode (OTP) sent to your mobile number. Permission to open the Account shall be determined by Company
              or its representatives, at their sole discretion. We may refuse to grant an application for an Account
              made by any person without giving a reason for such refusal. You agree and acknowledge that the decision
              of the Company in this regard shall be final. We may require additional identity verification procedures
              used to ensure that we can verify the identity of Users transacting with each other and assist our payment
              service providers corroborate User’s identity.
            </p>
            <p>
              Company reserves the right to deny or withdraw access to the Platform or Services to Users who fail to
              comply with the required verification procedures or if Company determines, at its sole discretion, that
              the User has failed to comply with the Terms.
            </p>
            <p>
              You agree and undertake that all information provided to Company is correct, complete, and accurate and
              that you will promptly update any such information if there is any change in it.
            </p>
            <p>
              You are solely responsible for maintaining the confidentiality of the password and other Account
              information and for restricting access to your computer or device. You agree to accept responsibility for
              all activities that occur under your Account. You are solely responsible for maintaining the
              confidentiality of your Account information and for restricting access to your computer or device. You
              shall immediately notify Company of any unauthorized use of your Account or any other breach of security.
              Company shall not be liable for any loss or damage arising from your failure to protect your Account
              information.
            </p>
            <p>
              You shall also be responsible for ensuring that all persons who access the Platform through your internet
              connection are aware of these Terms and comply with them.
            </p>
            <h2>D. Terms of Use</h2>
            <p>All Services provided by the Company are subject to the Terms of Use. You acknowledge and agree that:</p>
            <ul>
              <li>Content and Services offered on the Platform are for your personal and non-commercial use only.</li>
              <li>
                You agree not to use the Platform or Services in any manner that could damage, disable, overburden, or
                impair the Platform or interfere with any other party’s use and enjoyment of the Platform or Services.
              </li>
              <li>
                You shall not attempt to gain unauthorized access to the Platform or Services, other accounts, computer
                systems or networks connected to the Platform or Services through hacking, password mining, or any other
                means.
              </li>
              <li>
                You agree not to use any device, software, or routine that interferes with the proper functioning of the
                Platform or Services.
              </li>
              <li>
                You agree not to introduce any viruses, worms, Trojan horses, or other harmful code into the Platform or
                Services.
              </li>
              <li>
                You shall not use the Platform or Services to transmit any illegal, harmful, or offensive material.
              </li>
              <li>
                You shall not impersonate any person or entity or falsely state or otherwise misrepresent your
                affiliation with a person or entity.
              </li>
              <li>
                You agree to comply with all applicable laws and regulations while using the Platform and Services.
              </li>
              <li>
                Company reserves the right to remove or disable access to any Content that violates these Terms or is
                otherwise objectionable, at its sole discretion.
              </li>
            </ul>
            <h2>E. Privacy</h2>
            <p>
              Your use of the Platform and Services is subject to the Privacy Policy. The Privacy Policy describes how
              we collect, use, and protect your personal information.
            </p>
            <h2>F. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Company, its affiliates, directors, officers, employees, and
              agents shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or
              any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use,
              goodwill, or other intangible losses, resulting from:
            </p>
            <ul>
              <li>Your use or inability to use the Platform or Services.</li>
              <li>Any unauthorized access to or use of our servers and/or any personal information stored therein.</li>
              <li>Any interruption or cessation of transmission to or from the Platform or Services.</li>
              <li>Any bugs, viruses, or the like that may be transmitted to or through the Platform or Services.</li>
              <li>Any errors or omissions in any Content or Services.</li>
            </ul>
            <h2>G. Termination</h2>
            <p>
              Company reserves the right to terminate or suspend your access to the Platform and Services at any time,
              without prior notice or liability, for any reason, including but not limited to your breach of these
              Terms.
            </p>
            <p>
              Upon termination, your right to use the Platform and Services will immediately cease. If you wish to
              terminate your Account, you may do so by contacting us via email.
            </p>
            <h2>H. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising
              out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in
              India.
            </p>
            <h2>I. Contact Information</h2>
            <p>If you have any questions about these Terms or the Platform, please contact us at:</p>
            <p>
              Email: <a href='mailto:support@sportoni.com'>support@sportoni.com</a>
              <br />
              Address: Sportoni Technologies, [Insert Address], [City], [State], [Country], [PIN Code].
            </p>
          </div>
          <div>
            <h2>Payment Terms</h2>
            <section>
              <h3>Deposit in the User Wallet</h3>
              <p>
                In light of Rule 31B of the Central Goods and Services Tax Rules, 2017 (“CGST Rules“) effective from
                October 01, 2023, the Company shall levy applicable GST on the amount deposited by the User from the
                aforementioned effective date. The Company shall issue an invoice for such deposit to the User. The GST
                Invoice shall provide bifurcation of the amount deposited, i.e., the taxable value, and GST applicable
                on the said amount.
              </p>
              <p>
                When You deposit money to Your wallet on the Platform by using a Virtual Payment Address (VPA) of the
                Unified Payments Interface (UPI) payment method, We may store such VPA to facilitate seamless and swift
                deposit transactions for You in the future and for enhancing Your payment experience. You understand,
                agree and consent to such storing of the VPA by the Platform.
              </p>
              <p>
                The Platform may also, from time to time, through the Payment System Providers, fetch other VPAs
                associated with Your mobile number registered with the Platform. These VPAs will be used to facilitate
                seamless and swift deposit transactions for You and for enhancing Your overall payment experience. You
                understand, agree and consent to the Platform obtaining such VPAs from relevant Payment System Providers
                and storing and displaying such VPAs to You on the Platform.
              </p>
            </section>

            <section>
              <h3>Deposit in the User Wallet</h3>
              <p>
                In respect of any transactions entered into on the Platform for playing Games and contest(s), Users
                agree to be bound by the following payment terms to which Users shall be bound when participating in any
                game and the User will pay the contribution (Contribution) which will be inclusive of the following:
              </p>
              <ul>
                <li>
                  Pre-designated platform fee (Platform Fee) (for each kind of game hosted by the Company, as described
                  in within the Games) for access to the Platform.
                </li>
                <li>
                  Pre-determined Contribution towards the prize money pool (Prize Money Pool) of such game/contest as
                  stipulated by the Company, which will be passed on to the winner(s) of the game/contest after the
                  completion of the game/contest as per the terms and conditions thereto.
                </li>
              </ul>
              <p>
                Company reserves the right to deny its Platform/ Services to any User at its sole and absolute
                discretion. Such denial would automatically disqualify a User from playing any Games hosted on the
                Platform.
              </p>
              <p>
                Users by participating in any Games on the Platform hereby authorize and appoint CGames Customer
                Solutions LLP or a third-party escrow account as determined by the Company as their payment collection
                agent to collect and manage User funds for and on their behalf (Agent). For operational convenience, the
                Users’ directions (for collection and settlement of payments) will be communicated to the Agent through
                the Company (which will transmit the Users’ instructions to the Agent “as is”).
              </p>
              <p>
                Unless specifically identified in these terms, it is clarified that Company has no right or interest in
                this Prize Money Pool, and only acts as an intermediary engaged in collecting and distributing the Prize
                Money Pool in accordance with the game terms and conditions.
              </p>
            </section>

            <section>
              <h3>Payment Terms</h3>
              <p>
                In respect of any transactions entered into on the Platform, including making a payment to participate
                in the Games, the Users agree to be bound by the following payment terms:
              </p>
              <ul>
                <li>
                  Subject to these Terms, all amounts collected from the User are held in separate non-interest earning
                  bank account with an Agent. The said accounts are operated by the Agent (or a third party appointed by
                  the Company) in accordance with these Terms.
                </li>
                <li>
                  From these bank accounts, the payouts can be made to, (a) Users (towards their withdrawals of Winnings
                  or Play Money subject to applicable taxes); and (b) Company (towards its Platform Fees). The Agent
                  shall receive and hold the amounts of the Users in trust as a trustee of and for the benefit and use
                  of the Users.
                </li>
                <li>
                  Company receives only its share of the Platform Fees through the Agent and has no control over the
                  User funds held by the Agent in the dedicated non-interest earning bank account.
                </li>
                <li>
                  Company reserves the right to charge a Platform Fee, which would be specified and notified by it,
                  prior to a User’s joining of a game. The amount attributable towards Platform Fee will be debited from
                  the User’s wallet. The Platform Fee may be dynamic based on the type of game and dependent on factors
                  including without limitation, number of Users, eligibility criteria, ranking and server load etc.,
                  subject to the Platform Fee being determined before the commencement of a game.
                </li>
                <li>
                  The User may participate in a game wherein the User has to contribute a pre-specified Contribution
                  towards the Prize Money Pool of such game, which will be passed on to the winner(s) of the game after
                  the completion of the game as per the terms and conditions of such game. The amount to be paid-in by
                  the User towards the Prize Money Pool would also be debited from the User’s Account balance maintained
                  with the Agent.
                </li>
                <li>
                  Any User availing Services are provided with the following categories of accounts for the processing
                  and reconciliation of payments:
                  <ul>
                    <li>Play Money – comprises money deposited by the User through payment gateway (Play Money).</li>
                    <li>
                      Prize Money – comprises the money including in kind, won by the Users by winning the
                      game/contest(s) (Winnings). Winnings can be withdrawn after tax deduction, if applicable, or can
                      be utilized to play further game/contest(s).
                    </li>
                    <li>
                      Cashbacks – is a discount Scheme offered to Users by the company, as communicated from the company
                      from time to time (Cashbacks). Cashbacks given are non-withdrawable discounts/amounts, which can
                      be used to avail discount but by itself cannot be withdrawn. The Users cannot encash by redeeming
                      Cashbacks. It reflects the maximum discount that a User is eligible for subject to fulfillment of
                      specified conditions. Terms and Conditions of the Scheme will be communicated from time to time.
                      Cashback accrued will be separately credited in the Cashback account for monitoring the maximum
                      eligible discount. Cashback discount shall entitle User to a discount on platform fee capped at
                      maximum 90% (ninety percent) of the platform fee or such other % as communicated from time to
                      time.
                    </li>
                    <li>
                      Bonus – Bonus Money is a discount Scheme offered to a User by the company in the form of bonus
                      points or otherwise, as communicated to the company from time to time. Bonuses given are
                      non-withdrawable discounts, which can be used to avail discount but by itself cannot be withdrawn.
                      The Users cannot encash by redeeming Bonus points. It reflects the maximum discount that a User is
                      eligible for subject to fulfillment of specified conditions. Bonus Money can only be adjusted
                      towards the Platform Fee paid by the player for entering a tournament. (Bonus Money). Specific
                      terms and conditions of the Scheme will be communicated from time to time. Bonus Money accrued
                      will be separately credited in the Bonus Money account. The discount offered in the form of
                      Schemes itself cannot be withdrawn.
                    </li>
                  </ul>
                </li>
              </ul>
            </section>

            <section>
              <h3>Discount Schemes for Users of the Platform</h3>
              <p>
                The Company, at its sole discretion, may provide Discount Schemes, as offers for Users of the Platform
                from time to time. The Discount Schemes may be called Bonus, Cashbacks, Promotional offers and discounts
                etc. (Schemes) and details of the Schemes will be communicated to the Users accessing the platform
                before availing the Schemes. The said Schemes can be used by the Users on the Apps, subject to such
                terms and conditions as may be prescribed.
              </p>
              <p>
                The User will be eligible to avail and utilize the benefit of the Schemes offered by the Company,
                subject to fulfillment of all the terms and conditions attached for availment and utilization of each
                Schemes as communicated at the time of offer and acceptance of the Scheme by the User and the Company.
                Such terms and conditions may include details of such Schemes, their validity for availment/
                utilization, restriction in availment/ utilization when used in conjunction with other Schemes,
                discounts or vouchers etc. The terms and conditions of such Schemes may be changed or modified from time
                to time. Also, other general or special/ additional terms and conditions may apply to such offers, which
                will be communicated to the User beforehand. The User may avail Scheme on satisfying all the terms and
                Scheme conditions.
              </p>
              <p>
                In relation to the Services rendered on the Platform to the Users, the Company may offer an instant
                discount on the invoice or pre-agreed discount based on the Schemes. The said Schemes offered can be
                utilized by the User to avail discount against the Contribution/ Platform fees and/ or Prize Money Pool,
                as per the terms of Schemes offered.
              </p>
              <p>
                The quantum and conditions for availing and utilizing each offered Schemes will be communicated to the
                User before participating in a game or depositing Play Money.
              </p>
              <p>
                The Company shall be under no obligation to provide such offers and reserves the right to remove and
                modify such Schemes at any time.
              </p>
            </section>

            <section>
              <h3>Excess Payments</h3>
              <p>
                In case of any excess payment made by the User, such excess amount shall be available for the User to
                use for further participation or withdrawn, subject to applicable terms and conditions, including a
                valid payment request by the User. Users may review their wallet balance on the platform and utilize
                excess amounts for further participation or withdrawal.
              </p>
            </section>

            <section>
              <h3>Duplicate Credit Recovery</h3>
              <p>
                In the event of any duplicate crediting of winnings or other amounts to a User’s account, the Agent
                shall have the right to recover such duplicate amounts from the User’s account.
              </p>
            </section>

            <section>
              <h3>Withdrawal Requests</h3>
              <p>
                Users can withdraw funds by requesting the same through an email to the Company at its provided address,
                upon successful completion of identity verification and submission of necessary documents such as PAN
                card and bank details. Withdrawals will be processed in compliance with applicable GST and tax laws.
                Users are required to ensure that all withdrawal requests are accurate and in accordance with these
                Terms.
              </p>
            </section>

            <section>
              <h3>Refunds and Cancellations</h3>
              <p>
                In case of a refund request or game/contest cancellation, the Company may process refunds subject to any
                cancellation charges or applicable taxes. Users will be notified of the refund amount and process.
                Refunds will be issued in accordance with the terms specified for each game or contest.
              </p>
            </section>

            <section>
              <h3>TDS Compliance</h3>
              <p>
                As per tax regulations, TDS will be deducted at 30% on net winnings from the User’s account. The Company
                will provide TDS certificates for such deductions, subject to the availability of PAN details.
              </p>
            </section>

            <section>
              <h3>Tax Responsibility</h3>
              <p>
                Users are responsible for any additional taxes or liabilities arising from their winnings or
                participation in games. The Company may recover such taxes from the User’s account balance as necessary.
              </p>
            </section>

            <section>
              <h3>Verification and Documentation</h3>
              <p>
                Users winning prizes are required to provide valid identity and address proof. The Company may
                disqualify users based on the authenticity of the documents or other criteria.
              </p>
            </section>

            <section>
              <h3>Account Suspension</h3>
              <p>
                The Company reserves the right to suspend or block User accounts for unfair practices or violations of
                these Terms. Any amounts deposited may be forfeited as a result of such suspension or blocking.
              </p>
            </section>

            <section>
              <h3>Game Cancellation</h3>
              <p>
                In the event of game cancellation, the Contribution amount will be refunded to the User. The refund
                process will be conducted in accordance with the applicable terms and conditions.
              </p>
            </section>

            <section>
              <h3>Error in Transactions</h3>
              <p>
                Users are required to report any issues related to transactions within 24 hours via email. The Company
                will investigate and may process refunds within 7 business days if the issue is confirmed.
              </p>
            </section>

            <section>
              <h3>Intellectual Property</h3>
              <p>
                All intellectual property rights in Platform content, including software, materials, and designs, are
                owned by the Company and its affiliates. Unauthorized use of such intellectual property is prohibited.
              </p>
            </section>
          </div>
          <div>
            <h2>K. Payment Terms</h2>

            <h3>Deposit in the User wallet</h3>
            <p>
              In light of Rule 31B of the Central Goods and Services Tax Rules, 2017 ("CGST Rules") effective from
              October 01, 2023, the Company shall levy applicable GST on the amount deposited by the User from the
              aforementioned effective date.
            </p>
            <p>
              The Company shall issue an invoice for such deposit to the User. The GST Invoice shall provide bifurcation
              of the amount deposited, i.e., the taxable value, and GST applicable on the said amount.
            </p>
            <p>
              When You deposit money to Your wallet on the Platform by using a Virtual Payment Address (VPA) of the
              Unified Payments Interface (UPI) payment method, We may store such VPA to facilitate seamless and swift
              deposit transactions for You in the future and for enhancing Your payment experience. You understand,
              agree and consent to such storing of the VPA by the Platform.
            </p>
            <p>
              The Platform may also, from time to time, through the Payment System Providers, fetch other VPAs
              associated with Your mobile number registered with the Platform. These VPAs will be used to facilitate
              seamless and swift deposit transactions for You and for enhancing Your overall payment experience. You
              understand, agree and consent to the Platform obtaining such VPAs from relevant Payment System Providers
              and storing and displaying such VPAs to You on the Platform.
            </p>

            <h3>Deposit in the User wallet</h3>
            <p>
              In respect of any transactions entered into on the Platform for playing Games and contest(s), Users agree
              to be bound by the following payment terms to which Users shall be bound when participating in any game
              and the User will pay the contribution (Contribution) which will be inclusive of the following:
            </p>
            <ul>
              <li>
                Pre-designated platform fee (Platform Fee) (for each kind of game hosted by the Company, as described in
                within the Games) for access to the Platform.; and
              </li>
              <li>
                Pre-determined Contribution towards the prize money pool (Prize Money Pool) of such game/contest as
                stipulated by the Company, which will be passed on to the winner(s) of the game/contest after the
                completion of the game/contest as per the terms and conditions thereto.
              </li>
            </ul>
            <p>
              Company reserves the right to deny its Platform/ Services to any User at its sole and absolute discretion.
              Such denial would automatically disqualify a User from playing any Games hosted on the Platform.
            </p>
            <p>
              Users by participating in any Games on the Platform hereby authorize and appoint CGames Customer Solutions
              LLP or a third-party escrow account as determined by the Company as their payment collection agent to
              collect and manage User funds for and on their behalf (Agent). For operational convenience, the Users'
              directions (for collection and settlement of payments) will be communicated to the Agent through the
              Company (which will transmit the Users' instructions to the Agent "as is").
            </p>
            <p>
              Unless specifically identified in these terms, it is clarified that Company has no right or interest in
              this Prize Money Pool, and only acts as an intermediary engaged in collecting and distributing the Prize
              Money Pool in accordance with the game terms and conditions.
            </p>
            <p>
              In respect of any transactions entered into on the Platform, including making a payment to participate in
              the Games, the Users agree to be bound by the following payment terms:
            </p>
            <ul>
              <li>
                Subject to these Terms, all amounts collected from the User are held in separate non-interest earning
                bank account with an Agent. The said accounts are operated by the Agent (or a third party appointed by
                the Company) in accordance with these Terms.
              </li>
              <li>
                From these bank accounts, the payouts can be made to, (a) Users (towards their withdrawals of Winnings
                or Play Money subject to applicable taxes); and (b) Company (towards its Platform Fees). The Agent shall
                receive and hold the amounts of the Users in trust as a trustee of and for the benefit and use of the
                Users.
              </li>
              <li>
                Company receives only its share of the Platform Fees through the Agent and has no control over the User
                funds held by the Agent in the dedicated non-interest earning bank account.
              </li>
              <li>
                Company reserves the right to charge a Platform Fee, which would be specified and notified by it, prior
                to a User's joining of a game. The amount attributable towards Platform Fee will be debited from the
                User's wallet. The Platform Fee may be dynamic based on the type of game and dependent on factors
                including without limitation, number of Users, eligibility criteria, ranking and server load etc.,
                subject to the Platform Fee being determined before the commencement of a game
              </li>
              <li>
                The User may participate in a game wherein the User has to contribute a pre-specified Contribution
                towards the Prize Money Pool of such game, which will be passed on to the winner(s) of the game after
                the completion of the game as per the terms and conditions of such game. The amount to be paid-in by the
                User towards the Prize Money Pool would also be debited from the User's Account balance maintained with
                the Agent.
              </li>
            </ul>
            <p>
              Any User availing Services are provided with the following categories of accounts for the processing and
              reconciliation of payments:
            </p>
            <ul>
              <li>Play Money – comprises money deposited by the User through payment gateway (Play Money).</li>
              <li>
                Prize Money – comprises the money including in kind, won by the Users by winning the game/contest(s)
                (Winnings). Winnings can be withdrawn after tax deduction, if applicable, or can be utilized to play
                further game/contest(s).
              </li>
              <li>
                Cashbacks – is a discount Scheme offered to Users by the company, as communicated from the company from
                time to time (Cashbacks). Cashbacks given are non-withdrawable discounts/amounts, which can be used to
                avail discount but by itself cannot be withdrawn. The Users cannot encash by redeeming Cashbacks. It
                reflects the maximum discount that a User is eligible for subject to fulfillment of specified
                conditions. Terms and Conditions of the Scheme will be communicated from time to time. Cashback accrued
                will be separately credited in the Cashback account for monitoring the maximum eligible discount.
                Cashback discount shall entitle User to a discount on platform fee capped at maximum 90% (ninety
                percent) of the platform fee or such other % as communicated from time to time.
              </li>
              <li>
                Bonus – Bonus Money is a discount Scheme offered to a User by the company in the form of bonus points or
                otherwise, as communicated to the company from time to time. Bonuses given are non-withdrawable
                discounts, which can be used to avail discount but by itself cannot be withdrawn. The Users cannot
                encash by redeeming Bonus points. It reflects the maximum discount that a User is eligible for subject
                to fulfillment of specified conditions. Bonus Money can only be adjusted towards the Platform Fee paid
                by the player for entering a tournament. (Bonus Money). Specific terms and conditions of the Scheme will
                be communicated from time to time. Bonus Money accrued will be separately credited in the Bonus Money
                account. The discount offered in the form of Schemes itself cannot be withdrawn.
              </li>
            </ul>

            <h3>Discount Schemes for Users of the Platform:</h3>
            <p>
              The Company, at its sole discretion, may provide Discount Schemes, as offers for Users of the Platform
              from time to time. The Discount Schemes may be called Bonus, Cashbacks, Promotional offers and discounts
              etc. (Schemes) and details of the Schemes will be communicated to the Users accessing the platform before
              availing the Schemes. The said Schemes can be used by the Users on the Apps, subject to such terms and
              conditions as may be prescribed.
            </p>
            <p>
              The User will be eligible to avail and utilize the benefit of the Schemes offered by the Company, subject
              to fulfillment of all the terms and conditions attached for availment and utilization of each Schemes as
              communicated at the time of offer and acceptance of the Scheme by the User and the Company. Such terms and
              conditions may include details of such Schemes, their validity for availment/ utilization, restriction in
              availment/ utilization when used in conjunction with other Schemes, discounts or vouchers etc. The terms
              and conditions of such Schemes may be changed or modified from time to time. Also, other general or
              special/ additional terms and conditions may apply to such offers, which will be communicated to the User
              beforehand. The User may avail Scheme on satisfying all the terms and Scheme conditions.
            </p>
            <p>
              In relation to the Services rendered on the Platform to the Users, the Company may offer an instant
              discount on the invoice or pre-agreed discount based on the Schemes. The said Schemes offered can be
              utilized by the User to avail discount against the Contribution/ Platform fees and/ or Prize Money Pool,
              as per the terms of Schemes offered.
            </p>
            <p>
              The quantum and conditions for availing and utilizing each offered Schemes will be communicated to the
              User before participating in a game or depositing Play Money.
            </p>
            <p>
              The Company shall be under no obligation to provide such offers and reserves the right to remove and
              modify such Schemes at any time.
            </p>
            <p>
              The User voluntarily exercises the option to entail the benefit of the Schemes in the nature of discounts
              by participating in the game and redeeming the Schemes such as Bonus, Cashbacks, etc.
            </p>
            <p>
              Cashback and Bonus or any other method of calculating a Discount Schemes will not have any intrinsic value
              or any right of entitlement.
            </p>
            <p>
              In case there is any amount remaining to be paid by the User in relation to such User's participation in
              any game(s), the User will be taken to the designated payment gateway to give effect to such payment which
              shall also be credited to the Account maintained by the Agent. In case any amount added by the User
              through such payment gateway exceeds the remaining amount of the Contribution, the amount in excess shall
              be transferred to the Account and will be available for use in participation in the game(s) or for
              withdrawal in accordance with these Terms.
            </p>
            <p>
              Notwithstanding any other provisions, in cases where the Winnings are double credited to the Users
              Account, the User hereby undertakes, agrees, and authorizes the Agent to have the right to reclaim, impose
              lien and freeze the account of the User until the amount is re-claimed by the Agent.
            </p>
            <p>
              Debits from the Account for the purpose of enabling a User's participation in a game shall be made in
              order of the date of credit of amounts in the Play money, and accordingly, amounts credited into Play
              Money earlier in time shall be debited first.
            </p>
            <p>
              In order to request a withdrawal of any amount standing in the Play Money, the User must first complete
              Company's identity verification, and bank account verification, which will also require submission of
              User's PAN card and bank account details and by providing a reason for withdrawal over email. Company
              shall effect an online transfer to the User's bank account on record with Company by instructing the Agent
              on behalf of the User (to which the User expressly consents), within a commercially reasonable period of
              time. Such transfer will reflect as a debit to the User's Play Money. Pursuant to the provisions of Rule
              31B of the CGST Rules, the amount withdrawable by the User from Play Money will be net of GST paid on
              amount deposited w.e.f 01.10.2023.
            </p>
            <p>
              Company may, in certain exceptional circumstances and at its sole and absolute discretion, refund the
              amount to the User after deducting applicable cancellation charges and taxes, if any including GST on
              deposit.
            </p>
            <p>
              Company may, in certain exceptional circumstances and at its sole and absolute discretion, refund the
              amount to the User after deducting applicable cancellation charges and taxes, if any including GST on
              deposit.
            </p>
            <p>
              Further, withdrawal of any amount standing to the User's credit in the Winnings may be made by way of a
              request to the Agent through the Company. In such case, Company shall cause an online transfer to the
              User's bank account on record with the Company by instructing the Agent on behalf of the User (to which
              the User expressly consents), within a commercially reasonable period of time. Such transfer will reflect
              as a debit to the User's Winnings. For withdrawal of winnings from gaming, nominal amount of processing
              fee can be charged.
            </p>
            <p>
              Winners shall be contacted by the Company through the registered e-mail address of the Users. Users may be
              required to complete the verification process in order to raise the withdrawal request. As a general
              practice, winners will be required to verify their e-mail address & phone number along with following
              documents: (i) self-attested photocopy of the User's PAN card and (ii) bank account details and proof of
              the User. The list of winners shall be posted on a separate webpage on the Platform. The winners will also
              be intimated by e-mail.
            </p>
            <p>
              In the event that a User has been declared a winner on the Platform but has not received any communication
              from the Company, such User may contact the Company within the time specified on the Platform.
            </p>
            <p>
              Company shall not instruct the Agent to provide for withdrawal of a User's prize(s)/accumulated
              Winnings/Play Money unless the above-mentioned documents have been received and verified within the time-
              period stipulated by the Company. Only to those winners who successfully complete the verification process
              and provide the required documents within the time limit specified by the Company shall the Agent provide
              for (at the instructions of the Company on behalf of the User, to which the User expressly consents)
              withdraw/receive their accumulated Winnings/Play Money (or any part thereof).
            </p>
            <p>
              Users they will be required to provide valid photo identification and address proof documents for proof of
              identity and address in order for Company to process the withdrawal request. The name mentioned on the
              User's photo identification document should correspond with the name provided by the User at the time of
              registration on the Company Platform, as well as the name and address existing in the records of the
              User's bank account as provided to the Company. In the event that no bank account has been registered by
              the User against such User's Account with the Company, or the User has not verified his/her User Account
              with the Company, to the Company's satisfaction and in accordance with these Terms, Company shall provide
              such User with a notification to the User's email address as on record with the Company, and the User
              shall register a bank account with his/her User Account and/or to verify his/her User Account.
            </p>
            <p>
              Company shall scrutinise all documents submitted and may, at its sole and absolute discretion, disqualify
              any winner from withdrawing his accumulated Winnings (or any part thereof) on the following grounds:
            </p>
            <ul>
              <li>
                Determination by Company that any document or information submitted by the User is incorrect,
                misleading, false, fabricated, incomplete or illegible; or
              </li>
              <li>User does not fulfil the eligibility criteria; or</li>
              <li>Any other ground as reasonably determined by the Company.</li>
            </ul>
            <p>
              The User represents and warrants that the documents provided in the course of the verification process are
              true copies of the original documents to which they relate.
            </p>
            <p>
              Users are required to provide proper and complete details at the time of registration. Company shall not
              be responsible for communications errors, commissions or omissions including those of the Users due to
              which the results may not be communicated to the Winner.
            </p>
            <p>
              Where any of the fixtures within a game are cancelled or abandoned without an official result, all game
              entries are considered void, and the Contribution shall be duly refunded to User. There are no
              prize/Winnings pay-outs and platform fee charges for these voided Games.
            </p>
            <p>
              If, in a transaction performed by you on the Platform, money has been charged to your card or bank account
              and respective amount is not added to your Account within 24 hours of the completion of the transaction,
              then you shall inform us by sending an e-mail to care@ludowala.co from your registered e-mail address.
              Please include the following details in the e-mail – your (i) mobile number, (ii) transaction value, (iii)
              transaction date and (iv) transaction ID. Company will investigate the incident and, if it is found that
              money was indeed charged to your card or bank account without delivery of the balance in your Account,
              then you will be refunded the money within 7 business days from the date of receipt of your e-mail. All
              refunds will be credited to your Account.
            </p>
            <p>
              The Company may withdraw and / or cancel any contest(s) to be conducted or already conducted, without
              prior notice to any Users or winners of any Games / contest(s). In such an event, Company shall effect a
              refund of the amount of Contribution money contributed by each participant to be effected by instructing
              the Agent on behalf of the User (to which the User expressly consents).
            </p>
            <p>
              Applicability of tax deducted at source ('TDS') w.e.f April 01, 2023: As per the relevant provisions of
              the Income Tax Act, 1961 ('Act') read with rules and regulations thereunder, TDS is required to be
              deducted at the applicable rates in force on the "net winnings", whether in cash or in kind or partly in
              cash or partly in kind, of a user.
            </p>
            <p>
              Event of deductibility of taxes: TDS is required to be deducted on the Net Winnings at the time of every
              withdrawal from the User account and / or balance in the User account at the end of the financial year,
              from 'net winnings' comprised in the withdrawn amount and/ or balance at end of the financial year, as the
              case may be.
            </p>
            <p>
              Rate of TDS: TDS is required to be deducted at the rate of 30% (thirty percent) as prescribed by the
              Government of India under the Act or as prescribed under applicable laws, from time to time.
            </p>

            <p>
              User account: All the accounts/ wallets, by whatever name called, opened or maintained or operated by the
              User on the Platform.
            </p>

            <p>
              Withdrawal: Any amount withdrawn from a User Account maintained with Us to the User's bank account or any
              other accounts that belong to the User as may be used for any purpose other than online gaming. Any prize
              distributed in kind to the user will also be treated as an instance of withdrawal for the purposes of
              applicability and calculation of TDS.
            </p>

            <p>
              Dissemination of TDS certificates: The User (subject to the availability of valid PAN with the Company)
              shall be provided with the TDS certificate (Form 16A) in accordance with the applicable provisions.
            </p>

            <p>
              Changes proposed in law (if any): Aforementioned TDS related covenants are based on the understanding of
              the recently introduced provisions of the law. Company reserves its rights to modify/ change/ amend the
              TDS covenants in case of change in TDS provisions under Applicable law and apply TDS provisions applicable
              at the relevant time.
            </p>

            <p>
              Applicability of any other taxes: The User shall be responsible for bearing any other taxes as per
              applicable laws as amended from time to time (in addition to what is specified above). We reserve the
              right to recover taxes that become due and payable to the respective authority owing to any operation of
              law, demand by relevant authority or any judicial pronouncement or otherwise. We reserve the right to
              deduct the said amount from the User's account balance and deposit the tax with the government treasury.
            </p>

            <p>
              You represent and warrant to Us that You are not in the business or profession of gaming or playing games,
              and that any benefit/ perquisite received by You in form of discount, bonus money, cashback etc from Us is
              not arising from any business or exercising of a profession by You, for the purposes of section 194R of
              the (Indian) Income-tax Act, 1961.
            </p>

            <p>
              The decision of the Company with respect to the awarding of prizes shall be final, binding and
              non-contestable.
            </p>

            <p>
              To the extent permitted by law, Company makes no representations or warranties as to the quality,
              suitability or merchantability of any prizes and shall not be liable in respect of the same.
            </p>

            <p>
              The Company may, at their sole and absolute discretion, vary or modify the prizes being offered to
              winners, and Company has no control over the same. Users shall not raise any claim against the Company or
              question it's right to modify such prizes being offered, prior and after the closure of the Games.
            </p>

            <p>The winners shall bear all transaction charges levied for delivery of cash prizes.</p>

            <p>All prizes are non-transferable.</p>

            <h2>L. Prevention of Collusion and Fraud</h2>

            <p>We are committed to promoting fair play on our Platform.</p>

            <p>
              Our compliance team will track game play of all Users and strict action will be taken against any User(s)
              caught colluding. By agreeing to these Terms, you agree not to indulge in any unfair game practice that
              may provide undue advantage to you or any other User.
            </p>

            <p>
              In the event any User is found undertaking such activity on the Platform, Company shall be entitled, at
              its sole and absolute discretion, to suspend or terminate such User's account. Company reserves the right
              to permanently block the account of the User involved in such activity. Any amounts deposited by such User
              on the Platform shall stand forfeited. Company reserves the right to impose monetary penalties on Users
              found to be undertaking such practices on the Platform.
            </p>

            <p>
              We reserve the right to withhold any necessary action, as it deems fit, against Users found indulging in
              unfair means. The action could include, inter alia, monetary penalties, temporary account suspension,
              redemption blocking and/or permanent account deactivation. Any User involved in violation of these Terms
              is liable for prosecution.
            </p>

            <p>
              Depositing and withdrawing without playing any or a reasonable amount of Game(s) is a violation of our
              fair play deposit and withdrawal policy. Consecutive deposits and withdrawals are considered as money
              laundering actions, which is not permitted on the Platform. Any User found committing such an action is in
              violation of our fair play deposit and withdrawal policy and further to investigation is subject to a
              penalty fee.
            </p>

            <p>
              Any User deemed to be a fraud User for any reason, for example, found depositing or withdrawing from/to a
              fraudulent account, is subject to legal action from the Company's management including but not limited to
              the confiscation of the User's Account Balance and locking of the User's Account.
            </p>

            <p>
              Users caught dumping coins between accounts will be levied a minimum penalty of 40% of the coins dumped.
              Company reserves the right to permanently block the account and forfeit the coins (including pending
              withdrawals) available in it if the User is found to be involved in any kind of malicious activity /
              unfair game play. If you suspect any User colluding in any game or involved in unfair practices, you can
              contact us via email us at care@ludowala.co .
            </p>

            <p>
              By using the Platform, including any subdomains of the Platform, or related top-level domains including
              mobile sites, apps, APIs and widgets and/or registering yourself with us, you authorize us or our
              representatives to contact you via email or phone call or SMS including third party messaging apps to
              offer you our services including but not limited to impart product knowledge, offer/explain any
              promotional offers running on the Platform and offers offered by third parties, for which reasons,
              personally identifiable information may be collected. Irrespective of the fact that you have registered
              yourself under DND or DNC or NCPR service, you still authorize us or our representatives to contact you by
              any means aforementioned for the above-mentioned purposes or any other related purpose till the time you
              are registered with us or even after cessation of registration.
            </p>

            <h2>M. Intellectual Property</h2>

            <p>
              The Platform includes a combination of Content created by Company, its partners, affiliates, licensors,
              associates and/or Users. The intellectual property rights (Intellectual Property Rights) in all software
              underlying Company and the Platform and material published on the Platform, including (but not limited to)
              Games, games software, advertisements, written Content, photographs, graphics, images, illustrations,
              marks, logos, audio or video clippings and flash animation, is owned by Company, its affiliates, partners,
              licensors and/or associates. Users may not modify, publish, transmit, participate in the transfer or sale
              of, reproduce, create derivative works of, distribute, publicly perform, publicly display, or in any way
              exploit any of the materials or Content on Company either in whole or in part without express written
              consent from Company. Nothing in these Terms shall be construed to convey and the Users by virtue of these
              Terms shall not acquire any ownership or other interest or right in any intellectual property any of the
              materials or content on the Platform.
            </p>

            <p>Users may request permission to use any Content by writing in to helpdesk at care@ludowala.co .</p>

            <p>
              Users are solely responsible for all materials (whether publicly posted or privately transmitted) that
              they upload, post, e-mail, transmit, or otherwise make available on the Platform (Users Content). Each
              User represents and warrants that he/she owns all Intellectual Property Rights in the User's Content and
              that no part of the User's Content infringes any third-party rights. Users further confirm and undertake
              to not display or use of the names, logos, marks, labels, trademarks, copyrights or intellectual and
              proprietary rights of any third party on the Platform.
            </p>

            <p>
              Users agree to indemnify and hold harmless Company, its directors, officers, employees, affiliates and
              assigns from and against all costs, damages, loss and/ or harm including towards litigation costs and
              counsel fees, in respect of any third party claims that may be initiated including for infringement of
              Intellectual Property Rights arising out of such display or use of the names, logos, marks, labels,
              trademarks, copyrights or intellectual and proprietary rights on Company, by such User or through the
              User's commissions or omissions. We reserve the right to assume the exclusive defence and control of any
              matter otherwise subject to indemnification by you in which event you will assist and cooperate with
              Company in asserting any available defences.
            </p>

            <p>
              Users hereby grant to Company and its affiliates, partners, licensors and associates a worldwide,
              irrevocable, perpetual, royalty-free, non-exclusive, sub-licensable, license to use, store, reproduce,
              create derivative works of, distribute, publicly perform, publicly display, transfer, transmit, and/or
              publish Users' Content for any of the following purposes:
            </p>

            <ul>
              <li>displaying Users' Content on Platform;</li>
              <li>
                distributing Users' Content, either electronically or via other media, to other Users seeking to
                download or otherwise acquire it; and/or
              </li>
              <li>storing Users' Content in a remote database accessible by end Users, for a charge.</li>
            </ul>

            <p>
              This license shall apply to the distribution and the storage of Users' Content in any form, medium, or
              technology.
            </p>

            <p>
              The license shall not lapse due to non-use by Company whether under any provision of the Copyright Act,
              1957 or any other law.
            </p>

            <p>
              All names, logos, marks, labels, trademarks, copyrights or intellectual and proprietary rights on the
              Platform belonging to any person (including User), entity or third party are recognized as proprietary to
              the respective owners and any claims, controversy or issues against these names, logos, marks, labels,
              trademarks, copyrights or intellectual and proprietary rights must be directly addressed to the respective
              parties under notice to Company.
            </p>

            <h2>N. Testimonial Terms</h2>

            <p>
              Company may capture and obtain visual and/or audio recordings or performances, still images of the User,
              and text provided by the User for the testimonial being provided towards the Platform (the results of
              which are the Recordings). The Recordings provided by the User are voluntary and Company is the sole and
              exclusive owner of all rights in and to the Recordings, and all elements thereof (including, without
              limitation, the copyright thereto). Without prejudice to the above, the User grants to Company a perpetual
              royalty-free license, to publicly use, distribute, reproduce, create derivative works from, and
              perform/display the user's name, voice, likeness, appearance, biographical information, and other indicia
              of its identity as included in the Recordings and any excerpts or version thereof for their marketing, in
              any language, and without any geographical limitation. Company may incorporate the recordings and any
              separate content (e.g., quotes, photos, videos, artwork, materials, etc.) to market their Platform and
              Services. The User also hereby waives any right to inspect or approve the finished matter based on the
              Recording that may be used now or in the future, whether that use is known to the user or unknown.
            </p>

            <p>
              Company is not obligated to use the Recordings if it so wishes. The User will not attempt to enjoin or
              otherwise impair Company's use of the Recordings that is in accordance with this Release.
            </p>

            <h2>O. Third Party Sites, Services and Products</h2>

            <p>
              Platform may contain links to other Internet sites owned and operated by third parties. Users' use of each
              of those sites is subject to the conditions, if any, posted by such third-party sites. Company does not
              exercise control over any Internet sites apart from Company and cannot be held responsible for any content
              residing in any third-party Internet site. Company's inclusion of third-party Content or links to
              third-party Internet sites is not an endorsement by Company of such third-party Internet site.
            </p>

            <p>
              Users' correspondence, transactions/offers or related activities with third parties, including payment
              providers and verification service providers, are solely between the User and that third party. Users'
              correspondence, transactions and usage of the services/offers of such third party shall be subject to the
              terms and conditions, policies and other service terms adopted/implemented by such third party, and the
              User shall be solely responsible for reviewing the same prior to transacting or availing of the
              services/offers of such third party. User agrees that Company will not be responsible or liable for any
              loss or damage of any sort incurred as a result of any such transactions/offers with third parties. Any
              questions, complaints, or claims related to any third-party product or service should be directed to the
              appropriate vendor.
            </p>

            <p>
              The Platform contains Content that is created by Company as well as content provided by third parties.
              Company does not warranty the accuracy, integrity, quality of the content provided by third parties and
              such content may not be relied upon by the Users in utilizing the Services provided on the Platform
              including while participating in any of the Games hosted on the Platform.
            </p>

            <h2>P. Privacy</h2>

            <p>
              By using the Platform and providing any of your personal information to the Platform, You affirmatively
              consent and agree to comply with our Privacy Policy (link given above), guidelines and statements as may
              be applicable from time to time, which are incorporated into and forms an integral part of these Terms. If
              you do not agree to the terms of the Privacy Policy in its entirety or have objections to the use of your
              information, you may not access or otherwise use the Platform or its Services.
            </p>

            <h2>Q. Disconnection and Technical Issues</h2>

            <p>
              You understand and acknowledge that once a game has commenced, not being able to play due to slow internet
              connections, faulty hardware, technical failure due to customer's hardware, internet connection failure,
              low computer configuration or for any other reason not attributable to us does not require us to issue a
              refund of the participation amount you may have paid for participation.
            </p>

            <p>
              In case of any technical failures, server crashes, breakdowns, software defects, disruption or malfunction
              of service at our end, as a policy, we will cancel the Game(s) and refund the participation amounts after
              proper verification and no service fee will be charged for such Games and you accept that we are not
              responsible to you in all such cases. For any game, we have the right to cancel and refund the
              participation amount. In no case, other than a server crash, are we accountable for any of the User's
              disconnections from the server. We are also not liable for any prospective Winnings from any incomplete
              game.
            </p>

            <p>
              We do not hold any liability to any disconnection, lag, freeze or interference in network on the User's
              computer or any other external networks
            </p>

            <h2>R. Enforceability</h2>

            <p>
              By registering, you are considered to have accepted and understood all the Terms herein and the relevant
              Game specific rules and regulations. We recommend that you keep a copy of all transactions, gaming rules,
              cancellation and payment policies. Our failure or delay to act or exercise any right or remedy with
              respect to a breach of any of these Terms by you does not amount to surrendering or waiving our rights to
              act with respect to any prior, concurrent, subsequent or similar breaches.
            </p>

            <p>
              If any judicial or quasi-judicial body in India declares any of the provisions of these Terms to be
              unlawful, invalid, void or unenforceable for any reason, the validity and enforceability of the remaining
              provisions will not be affected. Any such inappropriate term or condition will be replaced with another
              term or condition that is valid and enforceable and is in most nearly with effect to the original invalid
              term. In such an event, the parties shall be obligated to construe and interpret the void, illegal or
              unenforceable provision with a valid, legal and enforceable provision in such manner that corresponds as
              closely as possible to Company's intent and objective in the void, illegal or unenforceable provisions.
            </p>
          </div>
          <div>
            <h2>S. Disclaimer of Warranties</h2>
            <p>
              Company disclaims any and all warranties, expressed or implied, in connection with the underlying software
              of the Platform, the Website and the Game(s), all of which are provided to the User as is.
            </p>

            <p>
              You agree that use of the Services and the access to the Platform is at Your own risk. The Services
              including the Platform, the Content, the Games, and any other materials contained on or provided through
              the Platform are provided "AS IS" and, to the fullest extent permitted by law, are provided without
              warranties of any kind, either express or implied. Without limiting the foregoing, Company does not make
              any warranties of fitness for a particular purpose, title, merchantability, completeness, availability,
              security, compatibility, or non-infringement; or that the Services will be uninterrupted, free of viruses,
              malware or other harmful components, accurate, error free or reliable.
            </p>

            <p>
              No person affiliated or claiming affiliation with the Platform has authority to extend such warranties.
            </p>

            <p>
              Without limiting the generality of the foregoing, to the maximum extent permitted by applicable law, we
              shall have no liability for any damages or injury caused, in whole or in part, by contingencies or issues
              beyond our reasonable control, including, but not limited to: the acts of third parties, errors in the
              Content or the Platform, network failures, internet failures, software and hardware failures, viruses and
              other system attacks, labor stoppages, riots, acts of government or god, natural disasters, acts of
              terrorism, communication line failure, or theft, destruction of, unauthorized access to, alteration of or
              use of records.
            </p>

            <p>
              To the maximum extent permitted by applicable law, you hereby agree that you shall have no remedy in
              respect of any statement, representation, assurance or warranty (whether made innocently or negligently)
              that is not set out in these Terms. You agree that you shall have no claim for innocent or negligent
              misrepresentation or negligent misstatement based on any statement in these Terms.
            </p>

            <p>
              The foregoing limitations shall apply regardless of whether (i) liability or damage is alleged for breach
              of contract, tortious behaviour, negligence, or under any other theory or cause of action, and/or (ii) the
              party against which liability or damages is sought was advised of the possibility thereof. For the
              avoidance of doubt, nothing in these Terms shall limit or exclude liability for (i) death or personal
              injury caused by negligence; or (ii) fraud.
            </p>

            <p>
              To the maximum extent permitted by applicable law, you agree that regardless of any statute or law to the
              contrary, any claim or cause of action arising out of or related to these Terms, the Platform, or any part
              thereof, must be asserted within one (1) year after such claim or cause of action arose, or it shall be
              forever barred.
            </p>

            <p>
              You agree and acknowledge that Company does not promise or ensure that you will be able to access your
              Account whenever you want. It is entirely possible that you may not be able to access your Account, or the
              Platform provided by Company at times or for extended periods of time due to, but not limited to system
              maintenance and updates.
            </p>

            <p>
              You agree and acknowledge that participation in the Games of skill hosted by the Company may result in
              financial loss to you. With full knowledge of the facts and circumstances surrounding the Game(s) hosted
              on the Platform, you are voluntarily participating in the Game(s) and assume all responsibility for it and
              risk resulting from your participation, including all risks of financial loss. Company makes no
              guarantees, warranties, representations, or other promises relating to the game(s) and assumes no
              liability or responsibility for any financial loss that you may sustain as a result of participation in
              the Game(s).
            </p>

            <p>
              You will be solely responsible for any delay and/or damage to your computer systems or loss of data that
              results from the installation of any software on your computer, and we expressly disclaim liability for
              any such failure and/or delay.
            </p>

            <p>
              You agree to assume the entire risk as to the results and performance of any software and/or Game(s)
              availed by you on the Platform. As such, the result and performance among other things depends on your
              internet connection and hardware. You also assume the entire cost of all servicing, repair and/or
              correction of your hardware when you access, download, or execute software or Game(s) available on the
              Platform. We explicitly disclaim liability for any delay or failure to perform resulting from installation
              of any software on your computer.
            </p>

            <p>You specifically acknowledge, agree and accept that we are not liable to you for:</p>
            <ol>
              <li>
                the defamatory, offensive or illegal conduct of any other User or for anything that turns out to be
                misleading, inaccurate, defamatory, threatening, obscene or otherwise illegal whether originating from
                another User or otherwise;
              </li>
              <li>any loss whatsoever arising from the use, abuse or misuse of your Account on our Platform;</li>
              <li>
                any loss incurred in transmitting information from you to our Platform by the Internet or by other
                connecting media;
              </li>
              <li>
                any technical failures, system breakdowns, defects, delays, interruptions, manipulated or improper data
                transmission, loss or corruption of data or communications' lines failure, distributed denial of service
                attacks, viruses or any other adverse technological occurrences arising in connection with your access
                to or use of our Platform;
              </li>
              <li>
                the accuracy, completeness or currency of any information services provided or any statistics shown on
                the Platform.
              </li>
            </ol>

            <h2>T. Indemnification and Limitation of Liability</h2>
            <p>
              You clearly understand and agree that Company shall under no circumstances (including, without limitation,
              in contract, negligence or other tort), be liable for any direct, indirect, ancillary, special,
              incidental, consequential or exemplary or punitive damages. This includes, but is not limited to injury,
              claim, loss of data, loss of income, loss of profit or loss of opportunity, loss of or damage to property,
              damages for monetary loss, goodwill, use, data or other intangible loss (even if Company has been advised
              of the possibility of such damages), resulting from or arising out of the use of or the inability to use
              the Platform, even if we have been advised or become aware of the possibility of such damages or loss or
              that such loss was foreseeable.
            </p>

            <p>
              You agree to indemnify us and each of our respective general and limited partners, Users, shareholders,
              directors, officers, employees, agents, representatives, vendors and business partners harmless from and
              against any and all claims, liabilities, obligations, losses, costs or debt, damages and expenses
              (including attorneys' fees and court costs) arising out of or relating to:
            </p>
            <ul>
              <li>
                breach of these Terms, in tort (including negligence) third party claims or liabilities arising against
                Company out of such a breach, based in contract, tort, statute, fraud, misrepresentation, or any other
                legal theory, and regardless of whether a claim arises during or after the termination of these Terms
              </li>
              <li>
                your use of the Platform in any matter that is contrary to applicable laws, with an intent to deceive,
                defraud cheat, mislead or solicit any business, monetary or non-monetary consideration or information
                from another User
              </li>
              <li>
                your breach of any applicable laws or governmental or judicial order which applies to your use of the
                Platform from a specific geography
              </li>
              <li>
                your use of the Platform, including but not limited to your posting, use of, modification or interaction
                with any content on the Platform
              </li>
              <li>
                any unauthorized, improper, illegal or wrongful use of your Account by any person, including a third
                party, whether or not authorized or permitted by you
              </li>
              <li>your User Content</li>
              <li>
                use by any other person accessing the Platform using your username or password, whether or not with your
                authorization
              </li>
              <li>the use by us of information provided by you through our Platform.</li>
              <li>
                from any income tax demand raised (including and not limited to tax, interest, penalty, withholding tax
                or any other amount payable under the Indian Income-tax Act, 1961) arising on account of your
                misrepresentation and/ or your non-compliance of the terms and conditions mentioned therein. You agree
                that any income tax demand (including and not limited to tax, interest, penalty, withholding tax or any
                other amount payable under the Indian Income-tax Act, 1961) which is paid/ payable by us in this regard,
                will be recovered by us and debited from your Play Money and Winnings.
              </li>
            </ul>

            <p>
              This indemnification obligation will survive the expiry or termination of these Terms and your use of the
              Platform.
            </p>

            <p>
              There could be instances where Company is not able to receive prompt updates about the change in
              applicable laws of your place of stay. It is your obligation to ensure that any activities you engage on
              the Platform are legal as per the applicable laws. You agree to indemnify and hold harmless, Company or
              its Platform, from any claim, demand, damage, or loss whatsoever coming out due to your non-compliance
              with the laws of your jurisdiction.
            </p>
          </div>
          <h2 className='mb-4 text-2xl font-bold'>U. Termination</h2>

          <p className='mb-4'>
            We may change, suspend or discontinue any aspect of the Platform at any time, including the availability of
            any Platform's feature, database, or Content. We may also impose limits on certain features and services or
            restrict your access to parts or the Platform, without notice or liability at any time in our exclusive
            discretion, without prejudice to any legal or equitable remedies available to us, for any reason or purpose.
            However, under normal circumstances, we will only do so where there has been conduct that we believe
            violates these Terms or other rules and regulations or guidelines posted on the Platform or conduct which we
            believe is harmful to other Users, to our businesses, or other information providers.
          </p>

          <p className='mb-4'>
            Upon any termination of these Terms, you shall immediately discontinue your use and access to the Platform
            and destroy all materials obtained from it. You hereby agree and consent to the above and agree and
            acknowledge that we can, at our sole discretion, exercise our right in relation to any or all of the above,
            and that we shall not be liable in any manner of the same; and you agree, acknowledge and consent to the
            same.
          </p>

          <p className='mb-4'>
            You acknowledge that your representations, undertakings, and warranties and the clauses relating to
            indemnities, limitation of liability, grant of license, governing law and jurisdiction, confidentiality
            shall survive the efflux of time and the termination of these Terms.
          </p>

          <h2 className='my-4 text-2xl font-bold'>v. Agreements with Escrow Agent, as applicable.</h2>

          <p className='mb-4'>
            Company shall enter into separate agreements with Agent/s for regulating their inter-se contractual
            obligations to give effect to these Terms from time to time, as it considers appropriate and necessary in
            its sole discretion. The Users are not and shall not be regarded as beneficiaries of such agreements. The
            Users shall have no privity of contract in connection with such agreements with the Company and Agents.
          </p>

          <h2 className='my-4 text-2xl font-bold'>W. Publicity</h2>

          <p className='mb-4'>
            Acceptance of a prize by the Winner constitutes permission for Company, and its affiliates to use the
            winner's name, likeness, voice, and comments for advertising and promotional purposes in any media worldwide
            for purposes of advertising and trade without any further permissions or consents and/or additional
            compensation whatsoever. The winners further undertake that they will be available for promotional purposes
            as planned and desired by the Company without any charge. The exact dates remain the sole discretion of the
            Company. Promotional activities may include but not be limited to press events, internal meetings and
            ceremonies/functions.
          </p>

          <h2 className='my-4 text-2xl font-bold'>X. Dispute Resolution</h2>

          <p className='mb-4'>
            In case you have any grievances with respect to the Platform or the Services, you can send an email to the
            Grievance Officer Mr. Sujal Kumar Tiwari (hereinafter referred to as the Grievance Officer) at{' '}
            <a href='mailto:grievances@ludowala.co' className='text-blue-600 hover:underline'>
              grievances@ludowala.co
            </a>
            . Further, you can write to the Nodal Officer Mr. Mayur Jangra (hereinafter referred to as the Nodal
            Officer) at{' '}
            <a href='mailto:nodal@ludowala.co' className='text-blue-600 hover:underline'>
              nodal@ludowala.co
            </a>
            . We reserve the right to replace the Grievance Officer and Nodal Officer at any time without any notice or
            intimation to you. You can directly escalate any disputes to our management team by contacting the Grievance
            or Nodal Officer.
          </p>

          <p className='mb-4'>
            Subject to the clauses below, the courts of competent jurisdiction at Haryana shall have exclusive
            jurisdiction to determine any and all disputes arising out of, or in connection with the Platform provided
            by Company (including the games, construction, validity, interpretation and enforceability of these Terms,
            or the rights and obligations of the Users), as well as the exclusive jurisdiction to grant interim or
            preliminary relief in case of any dispute referred to arbitration as given below. All such issues and
            questions shall be governed and construed in accordance with the laws of India.
          </p>

          <p className='mb-4'>
            In the event of any legal dispute (which may be a legal issue or question) which may arise, the party
            raising the dispute shall provide a written notification (Notification) to the other party. On receipt of
            Notification, the parties shall first try to resolve the dispute through discussions. In the event that the
            parties are unable to resolve the dispute within fifteen (15) days of receipt of Notification, the dispute
            shall be settled by arbitration.
          </p>

          <p className='mb-4'>
            The seat and venue of arbitration shall be Gurgaon, India. All arbitration proceedings shall be conducted in
            English and in accordance with the provisions of the Arbitration and Conciliation Act, 1996, as amended from
            time to time. The parties shall mutually appoint a sole arbitrator.
          </p>

          <p className='mb-4'>
            The arbitration award will be final and binding on the parties, and each party will bear its own costs of
            arbitration and equally share the fees of the arbitrator unless the arbitral tribunal decides otherwise.
          </p>

          <p className='mb-4'>
            The arbitrator shall be entitled to pass interim orders and awards, including the orders for specific
            performance and such orders would be enforceable in competent courts of Gurgaon. The arbitrator shall give a
            reasoned award.
          </p>

          <p className='mb-4'>
            Nothing contained in these Terms shall prevent Company from seeking and obtaining interim or permanent
            equitable or injunctive relief, or any other relief available to safeguard its interest prior to, during or
            following the filing of arbitration proceedings or pending the execution of a decision or award in
            connection with any arbitration proceedings from any courts of competent jurisdiction at Haryana to grant
            the same. The pursuit of equitable or injunctive relief shall not constitute a waiver on the part of Company
            to pursue any remedy for monetary damages through the arbitration described herein.
          </p>

          <h2 className='my-4 text-2xl font-bold'>Y. User Balances</h2>

          <p className='mb-4'>
            The User hereby consents to the transfer of his/her gameplay money balance(s) from the bank account of the
            existing escrow agent to a single nodal account (by whatever nomenclature, for the pooling of such gameplay
            money balance(s)) operated by any third party, Agent or an external escrow agent appointed by Company, and
            such gameplay money balance(s) shall be utilizable by the User on the Platform.
          </p>

          <p className='mb-4'>
            Notwithstanding anything contained in these Term or any other policies, but subject to applicable law, Users
            agree and acknowledge that should the User Account remain inactive for a period of [12 (twelve)] months,
            Company will transfer such amount in the User's gameplay money balances to a reserve account maintained by
            Company (Reserve Account) from which the User may claim such gameplay money balances, subject to the User's
            consent to additional KYC and user identification measures for claiming amounts from such Reserve Account.
            Company will notify the User of the existence of such unused balance and the transfer thereof 45
            (forty-five) days prior to the date of expiry of the Play Money amount by way of SMS, email, or call. The
            User agrees that if the User does not use the Services or utilize the gameplay money balances or request for
            a refund (where applicable), during such notice period then he/she consents to the transfer of the amount in
            the gameplay money balances, which shall be utilized by Company for spreading awareness on safety measures
            and best practices for online gaming.
          </p>
        </div>
      </div>
    </div>
  )
}
